#include "display/controls.h"

#ifdef __APPLE__
#define PRIMARY_MOD_LABEL "Cmd"
#else
#define PRIMARY_MOD_LABEL "Ctrl"
#endif

static const std::vector<ControlSection> control_sections{
    {"Playback",
     {{"Space", "Toggle play/pause"},
      {"(", "Toggle bidirectional in-buffer loop/pause"},
      {")", "Toggle forward-only in-buffer loop/pause"},
      {"J / L", "Reduce / increase playback speed (Shift: x1/5 step)"},
      {"A / ,", "Move to the previous frame in the buffer"},
      {"D / .", "Move to the next frame in the buffer"},
      {"Shift+A", "Seek to the previous frame (best with intra-frame formats)"},
      {"Shift+D", "Decode and advance one frame"}}},
    {"Seek",
     {{"Left / Right", "Seek 1 second backward / forward (Shift: x1/4 step)"},
      {"Down / Up", "Seek 10 seconds backward / forward (Shift: x1/4 step)"},
      {"Page Down / Page Up", "Seek 600 seconds backward / forward (Shift: x1/4 step)"}}},
    {"Sync",
     {{"\\", "Auto-align right video: search +/-0.5s around current left position"},
      {"[", "Auto-align backward: search the 1s range before current left position"},
      {"]", "Auto-align forward: search the 1s range after current left position"},
      {"+ / -", "Time-shift right video 1 frame forward / backward"},
      {"Shift + +/-", "Time-shift right video by 10 frames"},
      {"Alt + +/-", "Time-shift right video by 100 frames"}}},
    {"Display",
     {{"1 / 2", "Toggle hide/show left / right video"},
      {"H", "Toggle hide/show HUD"},
      {"I", "Toggle video info overlay"},
      {"O", "Toggle video/subtraction mode"},
      {"Alt+1", "Zoom to 1:1 pixels"},
      {"Alt+2", "Zoom 100% (x1)"},
      {"Alt+3", "Zoom 200% (x2)"},
      {"Alt+4", "Zoom 400% (x4)"},
      {"Alt+5", "Zoom 800% (x8)"},
      {"Alt+6", "Zoom 50% (x0.5)"},
      {"E", "Re-center view around mouse position"},
      {"R", "Global re-center and reset zoom to 100% (x1)"},
      {"Shift+Z", "Magnify area around cursor (shown in lower-left corner)"},
      {"Shift+C", "Magnify area around cursor (shown in lower-right corner)"},
      {"Q", "Toggle on-screen quality metrics overlay (PSNR/SSIM live, VMAF on pause)"},
      {"Y / Shift+Y", "Cycle through subtraction modes forward / backward"},
      {"U", "Toggle luminance-only subtraction mode"},
      {"Shift+M", "Cycle display mode (split / vstack / hstack)"},
      {"Shift+S", "Cycle aspect view mode"},
      {"Alt+T", "Toggle nearest-neighbor/bilinear video texture filtering"},
      {"Alt+I", "Toggle fast/high-quality resizing for input alignment"}}},
    {"Scopes",
     {{"F1 / Shift+1", "Toggle Histogram window"},
      {"F2 / Shift+2", "Toggle Vectorscope window"},
      {"F3 / Shift+3", "Toggle Waveform window"}}},
    {"Crop",
     {{"Shift+L", "Crop left video interactively"},
      {"Shift+R", "Crop right video interactively"},
      {"Shift+B", "Crop both videos to the same area"},
      {"K", "Auto-detect and crop black borders on both videos"},
      {"Backspace", "Clear crop(s)"}}},
    {"Sources",
     {{"S", "Swap left and right video"},
      {"Tab / Shift+Tab", "Cycle visual-right slot forward / backward through right pipelines"},
      {"Ctrl+Shift+1..0", "Switch directly to right video 1-10"},
      {"Z", "Toggle bottom video-picker dock (thumbnails + keep/skip/toss)"}}},
    {"Window",
     {{PRIMARY_MOD_LABEL "+Enter", "Toggle fullscreen"},
      {"Ctrl+W", "Restore startup window size"},
      {"Shift+W", "Restore saved window size"},
      {"Ctrl+Shift+W", "Save current window size"}}},
    {"Misc",
     {{"?", "Toggle on-screen help text for controls"},
      {"G", "Toggle FPS overlay"},
      {"Shift+G", "Print display state to console"},
      {"P", "Print mouse position and pixel value under cursor to console"},
      {"Shift+Q", "Print image similarity metrics to console"},
      {PRIMARY_MOD_LABEL "+S", "Save both frames and the on-screen content as images"},
      {"Shift+F", "Select a region and save cutouts as PNGs"},
      {PRIMARY_MOD_LABEL "+C", "Copy the current timestamp of the left video to the clipboard"},
      {PRIMARY_MOD_LABEL "+V", "Paste a timestamp from the clipboard and seek to that position"},
      {"Escape", "Quit"}}},
    {"Mouse Controls",
     {{"", "Move the mouse horizontally to adjust the movable slider position."},
      {"", "Use the mouse wheel to zoom in/out on the pixel under the cursor. Pan the view by moving the mouse while holding down the right button."},
      {"", "Left-click the mouse to perform a time seek based on the horizontal position of the mouse cursor relative to the window width (the target position is shown in the lower right corner)."},
      {"", "Shift-click to seek only the right video to the clicked position."}}},
    {"Other", {{"", "Hold Shift for smaller relative seek, playback-speed, and zoom adjustments where available. Availability may depend on conflicts with application shortcuts or operating system bindings."}}}};

const std::vector<ControlSection>& get_control_sections() {
  return control_sections;
}
