#include "display/controls.h"

#ifdef __APPLE__
#define PRIMARY_MOD_LABEL "Cmd"
#else
#define PRIMARY_MOD_LABEL "Ctrl"
#endif

static const std::vector<ControlSection> control_sections{
    {"Playback",
     {{"Space", "Play / pause"},
      {"(", "Bidir in-buffer loop"},
      {")", "Forward in-buffer loop"},
      {"J / L", "Speed -/+ (Shift: /5)"},
      {"A / ,", "Prev frame in buffer"},
      {"D / .", "Next frame in buffer"},
      {"Shift+A", "Decode prev frame"},
      {"Shift+D", "Decode next frame"}}},
    {"Seek",
     {{"Left/Right", "Seek +/-1s (Shift: /4)"},
      {"Down/Up", "Seek +/-10s (Shift: /4)"},
      {"PgDn/PgUp", "Seek +/-600s (Shift: /4)"}}},
    {"Sync",
     {{"\\", "Auto-align symmetric"},
      {"[", "Auto-align backward"},
      {"]", "Auto-align forward"},
      {"+ / -", "Shift right +/-1 frame"},
      {"Shift +/-", "Shift right +/-10"},
      {"Alt +/-", "Shift right +/-100"}}},
    {"Display",
     {{"< / >", "Hide left / right"},
      {"H", "Hide HUD"},
      {"I", "Info overlay"},
      {"O", "Subtraction mode"},
      {"Alt+1", "Zoom 1:1"},
      {"Alt+2", "Zoom 100%"},
      {"Alt+3", "Zoom 200%"},
      {"Alt+4", "Zoom 400%"},
      {"Alt+5", "Zoom 800%"},
      {"Alt+6", "Zoom 50%"},
      {"E", "Recenter on mouse"},
      {"R", "Recenter + reset zoom"},
      {"Shift+Z", "Magnify (lower-left)"},
      {"Shift+C", "Magnify (lower-right)"},
      {"Q", "Quality overlay"},
      {"Y / Shift+Y", "Cycle subtract mode"},
      {"U", "Luma-only subtract"},
      {"Shift+M", "Cycle display mode"},
      {"Shift+S", "Cycle aspect mode"},
      {"Alt+T", "Texture filter"},
      {"Alt+I", "Align filter"}}},
    {"Scopes",
     {{"F1 / Shift+1", "Histogram"},
      {"F2 / Shift+2", "Vectorscope"},
      {"F3 / Shift+3", "Waveform"}}},
    {"Crop",
     {{"Shift+L", "Crop left"},
      {"Shift+R", "Crop right"},
      {"Shift+B", "Crop both"},
      {"K", "Auto-crop black"},
      {"Backspace", "Clear crops"}}},
    {"Sources",
     {{"S", "Swap left / right"},
      {"Tab", "Cycle right slot"},
      {"Shift+Tab", "Cycle right (back)"},
      {PRIMARY_MOD_LABEL "+1..0", "Pick right 1-10"},
      {PRIMARY_MOD_LABEL "+Right", "Focus next right"},
      {PRIMARY_MOD_LABEL "+Left", "Focus prev right"},
      {"Z", "Toggle bottom dock"}}},
    {"Dock",
     {{"`", "Focus left video"},
      {"M", "Keep focused"},
      {"B", "Toss focused"},
      {"N", "Skip focused"},
      {"X", "Keep focused, toss rest"},
#ifdef __APPLE__
      {PRIMARY_MOD_LABEL "+R", "Reveal in Finder"}
#else
      {PRIMARY_MOD_LABEL "+R", "Reveal in Finder (macOS)"}
#endif
     }},
    {"Window",
     {{PRIMARY_MOD_LABEL "+Enter", "Toggle fullscreen"},
      {"Ctrl+W", "Restore startup size"},
      {"Shift+W", "Restore saved size"},
      {"Ctrl+Shift+W", "Save window size"}}},
    {"Misc",
     {{"?", "Toggle this help"},
      {"G", "FPS overlay"},
      {"Shift+G", "Print display state"},
      {"P", "Print pixel at cursor"},
      {"Shift+Q", "Print metrics"},
      {PRIMARY_MOD_LABEL "+S", "Save frames + OSD"},
      {"Shift+F", "Save selected region"},
      {PRIMARY_MOD_LABEL "+C", "Copy timestamp"},
      {PRIMARY_MOD_LABEL "+V", "Paste timestamp + seek"},
      {"Escape", "Quit"}}},
    {"Mouse",
     {{"", "Right-drag: pan"},
      {"", "Wheel: zoom on cursor"},
      {"", "Left-click: seek to position"},
      {"", "Shift+click: seek right video only"}}},
    {"Notes",
     {{"", "Hold Shift for finer seek / speed / zoom."}}}};

const std::vector<ControlSection>& get_control_sections() {
  return control_sections;
}
